New epromstore
OpenAstroTech/OpenAstroTracker-Firmware pull request #10
Opened 2020-12-18 18:57 UTC by philharrisathome

New EEPROMStore implementation, abstracting all scaling and low-level store management away from Mount etc.

- EEPROMStore is now guaranteed to return a valid value for any item, regardless of whether it is present in NVM or not. This simplifies Mount considerably.
- Implementation is transaction-based such that flag setting & item value storing occurs in an atomic fashion through commit() (at least on ESP32).
- Quietened noisy CTORs in DayTime and added assignment operator.

2020-12-18 20:54 UTC, ClutchplateDude commented
Hey, Phil (I assume that's your name). Are you active on our Slack channel? It'd be great to have you in the #oat-development channel so we can talk about stuff we're working on and don't duplicate work, etc. Plus we're a fun group....hehe.

2020-12-18 22:04 UTC, ClutchplateDude requested changes

2020-12-18 22:04 UTC, ClutchplateDude commented on Configuration_adv.hpp
> +// #define DEBUG_LEVEL (DEBUG_INFO)
Can't check this in :-) Please reset to DEBUG_NONE

2020-12-18 22:04 UTC, ClutchplateDude commented on src/b_setup.hpp
> +    vTaskDelay(1);  // 1 ms 	// This will limit max stepping rate to 1 kHz
I think we decided to remove this line....

2020-12-18 23:36 UTC, philharrisathome commented
I think the vTaskDelay(1) in stepperControlTask() is required to avoid blocking the core. I still need to check this. It was mentioned that stepping was not smooth with this present - can you elaborate on the symptoms so I know what to look for?

2020-12-18 23:39 UTC, philharrisathome commented
I am a Phil btw, nice to meet you! I'm on the slack channel but haven't been active. I do want to make sure I sync with you guys - have got a bit carried away the last days while understanding how this thing works. It is a pretty cool project!

2020-12-19 00:22 UTC, philharrisathome commented
My github workflow needs some work :disappointed:. I have added a new PR that correctly merges the "fixing-steps-per-degree" and "new-epromstore" into develop without conflicts. You may want to decline this one.
I have not yet resolved the question over vTaskDelay().

2020-12-19 01:09 UTC, closed without merging