Log cleanup
OpenAstroTech/OpenAstroTracker-Firmware pull request #161
Opened 2022-01-19 17:27 UTC by ClutchplateDude

- Cleaned up logging somewhat
- Ensured all log messages have a category start word.
- Ensured all log messages are stored in Flash memory.

2022-01-20 08:24 UTC, andre-stefanov requested changes
Maybe we could place tags into [...] ?

2022-01-20 08:24 UTC, andre-stefanov commented on src/WifiControl.cpp
> +            LOGV2(DEBUG_WIFI, F("WIFITCP: Available bytes %d. Peeking."), client.available());
should not this be `WIFI: TCP:` or `[WIFI][TCP]` ?

2022-01-20 08:24 UTC, andre-stefanov commented on src/WifiControl.cpp
> +              F("WIFIUDP: Received %d bytes from %s, port %d"),
same as with tcp

2022-01-23 16:41 UTC, cameronswinoga commented
Could you rename your commit message to have the same version number as the actual version? (`2.10.4` vs `1.10.4`)

2022-01-23 16:41 UTC, cameronswinoga approved these changes
Could you rename your commit message to have the same version number as the actual version? (`2.10.4` vs `1.10.4`)

2022-01-26 21:11 UTC, merged