actually allow for override of SUPPORT_POINTS_OF_INTEREST
OpenAstroTech/OpenAstroTracker-Firmware pull request #172
Opened 2022-02-13 07:11 UTC by anjok

You can't override SUPPORT_POINTS_OF_INTEREST in your Configuration_local.hpp as you'd get compilation errors.

2022-02-13 17:03 UTC, cameronswinoga requested changes

2022-02-13 17:03 UTC, cameronswinoga commented on Changelog.md
> +- Actually allow for override of SUPPORT_POINTS_OF_INTEREST.
Please remove the word `Actually`

2022-02-13 17:03 UTC, cameronswinoga commented on Configuration_adv.hpp
> +        // If this is set to 0 you still have a GO menu that has Home and Park.
Please move the explanation above the `#ifndef`

2022-03-19 19:33 UTC, ClutchplateDude commented
This seems abandoned, or author is not responding. New PR created by OAT devs.

2022-03-19 19:33 UTC, closed without merging