Ra homing lcd
OpenAstroTech/OpenAstroTracker-Firmware pull request #193
Opened 2022-09-29 06:31 UTC by ClutchplateDude

- Added RA Autohoming support to Guided startup
- Added DEC Offset homing support to Guided startup
- Defaulted Auto-home questions to YES on LCD during Guided Startup
- Fixed bug that did not honor TrackingOffOnBoot flag when using Guided startup

- Added DEC Offset homing support to CTRL menu
- Removed SetParkingPos from CAL menu
- Added SetDecHomingOffset to CAL menu
- Fixed Park command to actually park DEC after homing
- Fixed a bug that made DEC parking go in the wrong direction
- Made Unpark go to home position after enabling Tracking

- Fixed SetLimit commands to actually use passed limits
- Fixed bug that did not change submenu items in the CTRL menu as button up and down were pressed
- Renamed some menu items for clarity and consistency

2022-09-29 14:31 UTC, julianneswinoga approved these changes, later dismissed

2022-09-29 14:31 UTC, julianneswinoga commented on Version.h
> +#define VERSION "V1.13.1"
Could you explain the version bump? 13 vs 12, and why a minor and not just patch?

2022-09-29 14:31 UTC, julianneswinoga commented on src/Mount.cpp
> +            LOG(DEBUG_STEPPERS, "[STEPPERS]: MoveSteppersTo: DEC Lower Limit enforced. To: %f", _decLowerLimit);
`%f` should be `%l`

2022-09-29 14:31 UTC, julianneswinoga commented on src/c65_startup.hpp
>      switch (startupState)
Just want to double check that you've tested the LCD with gyro level and auto-home. (I know you usually don't have an LCD)

2022-09-29 16:22 UTC, ClutchplateDude commented on Version.h
> +#define VERSION "V1.13.1"
I had 12 in another branch, but I guess I could go with 12 here. Given that it has some new features I thought a minor number change was appropriate

2022-09-29 16:22 UTC, ClutchplateDude commented on src/Mount.cpp
> +            LOG(DEBUG_STEPPERS, "[STEPPERS]: MoveSteppersTo: DEC Lower Limit enforced. To: %f", _decLowerLimit);
Oooh, good catch!

2022-09-29 16:23 UTC, ClutchplateDude commented on src/c65_startup.hpp
>      switch (startupState)
Actually, that's one combo I have not tested. Will do so today.

2022-09-29 17:48 UTC, julianneswinoga commented on Version.h
> +#define VERSION "V1.13.1"
Yeah I agree, large change but just wanted to make sure we were thinking the same thing. Minor version 12 makes sense. Keep it in order

2022-09-30 19:49 UTC, julianneswinoga requested changes

2022-09-30 19:49 UTC, julianneswinoga commented on Version.h
> +#define VERSION "V1.12.1"
Looking at our previous version bumps, this should be 1.12.0 (not 12.1)

2022-11-08 03:38 UTC, ClutchplateDude commented on src/c65_startup.hpp
>      switch (startupState)
I can't rewire my gyro level....

2022-11-13 20:57 UTC, julianneswinoga commented on src/c65_startup.hpp
>      switch (startupState)
If we're making changes here but can't test them, I'm not sure we should be making those changes

2022-11-13 20:59 UTC, julianneswinoga requested changes
Just need someone to test the LCD + gyro combination if we want those changes. Perhaps someone from the discord community would be willing?

2022-11-23 08:11 UTC, ClutchplateDude commented on src/c65_startup.hpp
>      switch (startupState)
So basically stop development on LCD code?

2022-12-04 23:46 UTC, andre-stefanov requested changes

2022-12-04 23:46 UTC, andre-stefanov commented on src/Mount.cpp
> +        if (slewStatus() == SLEWING_TRACKING)
`isSlewingTRK()` ?

2023-01-20 17:22 UTC, ClutchplateDude commented on src/Mount.cpp
> +        if (slewStatus() == SLEWING_TRACKING)
Yes

2024-02-17 18:31 UTC, closed without merging