Improved UART TX test
OpenAstroTech/OpenAstroTracker-Firmware pull request #83
Opened 2021-03-24 13:46 UTC by CTetford

Add configurable option to UART TX test to specify approximate degrees of test rotation

2021-04-14 15:40 UTC, ClutchplateDude submitted a review, later dismissed

2021-04-19 23:18 UTC, andre-stefanov commented
mh it is possible to enable both test types at the moment. we should use an enumeration for the test type (e.g. values defined in Constants.hpp like for other hardware stuff).

2021-04-19 23:18 UTC, andre-stefanov commented
5° on DEC is good visible but on RA i had to really pay close attention when not seeing the oat from the front (which is the case for some builds).

2021-04-19 23:20 UTC, andre-stefanov requested changes
mh it is possible to enable both test types at the moment. we should use an enumeration for the test type (e.g. values defined in Constants.hpp like for other hardware stuff).

2022-02-11 14:00 UTC, julianneswinoga requested changes

2022-02-11 14:00 UTC, julianneswinoga commented on src/Mount.cpp
> +    int _speed = (DEC_STEPPER_SPEED / 2)
Local variables shouldn't start with an underscore

2022-02-11 14:00 UTC, julianneswinoga commented on src/Mount.cpp
> +    int _speed = (DEC_STEPPER_SPEED / 2)
You should add `const` to these local variables

2022-02-11 14:00 UTC, julianneswinoga commented on src/Mount.cpp
> +                 / 0.715255737f;  //microsteps per driver clock tick (From TMC2209 datasheet: v[Hz] (microstep/s) = VACTUAL[2209] * 0.715Hz)
Could you move these comments to the line above the variable? That way you don't need to add line breaks in the middle of the expression

2022-02-11 14:00 UTC, julianneswinoga commented on src/Mount.cpp
> +{  //Runs motor at specified speed for specified duration in each dirction, allowing 0.5s to stop motion after each move
This comment should go above the function, ideally in docblock format:
```C++
/**
 * Runs motor at specified speed for specified duration in each direction, allowing 0.5s to stop motion after each move
 * @param[in,out] driver The stepper driver instance
 * @param[in] speed The speed to run the stepper motor at (in deg/s? idk)
 * @param[in] duration The amount of time to turn the stepper, in seconds
 */
void Mount::testUART_vactual(TMC2209Stepper *driver, int speed, int duration)
{
```

2022-02-13 09:53 UTC, andre-stefanov approved these changes

2022-02-13 15:55 UTC, andre-stefanov requested changes, later dismissed
Oops

2022-02-14 14:46 UTC, CTetford commented on src/Mount.cpp
> +{  //Runs motor at specified speed for specified duration in each dirction, allowing 0.5s to stop motion after each move
Done

2022-02-14 14:46 UTC, CTetford commented on src/Mount.cpp
> +                 / 0.715255737f;  //microsteps per driver clock tick (From TMC2209 datasheet: v[Hz] (microstep/s) = VACTUAL[2209] * 0.715Hz)
Done

2022-02-14 14:46 UTC, CTetford commented on src/Mount.cpp
> +    int _speed = (DEC_STEPPER_SPEED / 2)
Done

2022-02-14 15:16 UTC, cameronswinoga commented on src/Mount.cpp
> +{  //Runs motor at specified speed for specified duration in each dirction, allowing 0.5s to stop motion after each move
? I don't see it changed haha

2022-02-14 16:37 UTC, CTetford commented on src/Mount.cpp
> +{  //Runs motor at specified speed for specified duration in each dirction, allowing 0.5s to stop motion after each move
Sorry - my bad, I skipped one lol

2022-02-14 16:43 UTC, cameronswinoga requested changes

2022-02-14 16:43 UTC, cameronswinoga commented on src/Mount.cpp
> + * @param[in] speed The speed to run the stepper motor at (in deg/s? idk)
Could you modify the comment to reflect what the function does? I just wrote out a basic structure that you could fill in

2022-02-14 18:32 UTC, cameronswinoga approved these changes

2022-02-14 19:01 UTC, merged